<?xml version="1.0" encoding="utf-8"?><Database Name="WeightControl" Class="WeightControlClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\WeightControl.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WeightControlConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Weights" Member="Weights">
    <Type Name="Weight">
      <Column Name="Id" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Weight" Member="BodyWeight" Storage="_Weight1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>